### ISSUE TITLE
No module caccomf

### ISSUE THREAD

**Issue by gVallverdu** [MaginnGroup/PyLAT#1]
Hi
I am trying to use your PyLAT modules. I ran the test about viscosity but I obtain the following error:
```
Traceback (most recent call last):
  File "../PyLAT/PyLAT.py", line 37, in <module>
    from src.calcCOM import calcCOM
  File "/home/r/user/g/xxxx/Acetonitrile/PyLAT/src/calcCOM.py", line 26, in <module>
    import calccomf
ImportError: No module named 'calccomf'
```

Looking at your repository, there is not any calccomf module. Could you please precise what is this module ?
Thanks

**Comment by mike5603** [comment]
The calccomf module is created when compiling the FORTRAN codes using either compile.sh or compile.py

**Comment by gandhiforbes** [comment]
Dear Sir,
I am also getting the same problem:
-----------------------------------------------------
Traceback (most recent call last):
  File "PyLAT.py", line 43, in <module>
    from src.calcCOM import calcCOM
  File "/mnt/g/LAMMPS/PyLAT/PyLAT-master/src/calcCOM.py", line 26, in <module>
    import calccomf
ImportError: No module named 'calccomf'
-----------------------------------------------------------------------
You mentioned calccomf module is created after compiling compile.sh or compile.py.
Name of the file created: calccomf.cpython-35m-x86_64-linux-gnu

Now how to get rid of this error?
