### ISSUE TITLE
Is the PyLAT suitable for parallel computing in HPC system

### ISSUE THREAD

**Issue by Yongxiancheng** [MaginnGroup/PyLAT#13]

**Comment by Yongxiancheng** [comment]
I am really appreciate for the open program and have compiled the PyLAT program in my school's HPC. But I found that the program seems not be able to run in parallel. Is it right or it is my problem?

Meanwhile, I have another question remains:  If there is a system contains five molecule types, would it be possible to calculate the properties of the two specified type in the system? Or is it only able to calculate all the molecule types in the system?

**Comment by mike5603** [comment]
As of right now PyLAT is only serial for most properties. I think there might be some old code in viscio.py to parallelize the viscosity calculation. You can set the NCORES variable for up to 6 cores. Anything beyond that would not speed up the calculations at all.

For the second part of your questions, if I understand you correctly, you want to calculate something like diffusivity, and only care about two molecule types in the system? As of right now there is no way to limit the calculation to  a subset of the system.

**Comment by Yongxiancheng** [comment]
Thanks for your reply. I hope that the program would be better and applied wider in the furture.
