### ISSUE TITLE
the computing equation of viscosity in the viscio.py

### ISSUE THREAD

**Issue by Yongxiancheng** [MaginnGroup/PyLAT#16]
When I use the program to calculate the viscosity, I found that the viscosity calculation is using the file viscio.py, and the formula is as follow:

        numtimesteps = len(self.llog['pxy'])
        calcsteps = np.floor((numtimesteps-cutoff)/10000)*10000
        cutoff = int(numtimesteps - calcsteps)
        a1=self.llog['pxy'][cutoff:]
        a2=self.llog['pxz'][cutoff:]
        a3=self.llog['pyz'][cutoff:]
        a4=self.llog['pxx'][cutoff:]-self.llog['pyy'][cutoff:]
        a5=self.llog['pyy'][cutoff:]-self.llog['pzz'][cutoff:]
        a6=self.llog['pxx'][cutoff:]-self.llog['pzz'][cutoff:]
        array_array=[a1,a2,a3,a4,a5,a6]
        pv=p.map(autocorrelate,array_array)
        **pcorr = (pv[0]+pv[1]+pv[2])/6+(pv[3]+pv[4]+pv[5])/24**
   	 
        temp=np.mean(self.llog['temp'][cutoff:])
       
        visco = (cumtrapz(pcorr,self.llog['step'][:len(pcorr)]))*self.llog['timestep']*10**-15*1000*101325.**2*self.llog['vol'][-1]*10**-30/(1.38*10**-23*temp)
        Time = np.array(self.llog['step'][:len(pcorr)-1])*self.llog['timestep']
        p.close()
        return (Time,visco)

The bolded equation is confusing me because I only know the viscosity calculation can use (pxy+pxz+pyz)/3. And I can't find anymore information in your PyLAT article published in JCIM.

Would it be possible for you to simply explain the meaning of the formula or give me the original document of this equation?

**Comment by Yongxiancheng** [comment]
Seems like the equation is not bolded. What I mentioned before is the equation:
pcorr = (pv[0]+pv[1]+pv[2])/6+(pv[3]+pv[4]+pv[5])/24

Thanks for your consideration and time.

**Comment by mike5603** [comment]
@zhangyongND Can correct me if I am wrong about this but I think it comes from the following:

This equation comes out of the rotational invariance of the system. Due to the rotational invariance, we can include three more elements of the stress tensor [1/2(Pxx-Pyy),1/2(Pyy-Pzz),1/2(Pxx-Pzz)] . By averaging over all six elements instead of just Pxy Pyz and Pxz, we can get these calculations to converge much more quickly.

**Comment by mike5603** [comment]
This equation is after the dot product and averaging, so it is 1/2(Pxx[t0]-Pyy[t0])*1/2(Pxx[t0+t]-Pyy[t0+t]) = 1/4(Pxx[t0]-Pyy[t0])*(Pxx[t0+t]-Pyy[t0+t]) hence 24 instead of 12

**Comment by Yongxiancheng** [comment]
Thank you for providing all useful informaiton. That helps a lot.
