### ISSUE TITLE
The arrangement of molecule id

### ISSUE THREAD

**Issue by Yongxiancheng** [MaginnGroup/PyLAT#17]
In the README.md, there is one sentence-- Also required is the name and number of each molecule type in the system. To do this, use the --mol and --nummol flags. Use **the same order** as they were entered into the data file. 
Here is my little question, if the order of type in the data is 1-Na, 2-K, 3-Cl. While the order of molid is disordered, which means the molids are 1-Na, 2-K, 3-Na, 4-Cl, 4-K, 5-Cl, 6-Cl, 7-Cl, 8-Cl.
Than I used the code --nummol 2 --nummol 2 --numnol 4 --mol Na --mol K --mol Cl. Woule the calculation automatically identify the molid 1-Na and 3-Na as the input code "--mol  Na", or the input code "--mol Na" would appoint the molid 1-Na and 2-K?

**Comment by mike5603** [comment]
The code identifies molecule type based on the molecule id, and it assumes that all of the molecules are sequential. So for your example, it would assume that molecules 1 and 2 would be Na, 3 and 4 would be K and 5-8 would be Cl. This is consistent with the output of packmol, which is by far the most widely used initialization code.

**Comment by Yongxiancheng** [comment]
Thank you for your kind reply. I will try to obey the rule of the program.
