### ISSUE TITLE
Referenced example files missing

### ISSUE THREAD

**Issue by matteo-northvolt** [MaginnGroup/PyLAT#18]
Hello,

is it possible to have access to the files mentioned in the example you provide?

```
python PyLAT.py -d -g --mol H2O --mol CH3OH --nummol 500 --nummol 500
-p methanol/inwater/ -f methanolwater.json -v 2 mol.log restart.dat mol1.lammpstrj mol2.lammpstrj
```

I am having some difficulties in using PyLAT and especially in the definition of `--mol` and `--nummol` keys (I tried to follow the solution reported in issue #10, but I am still not sure about the results).

Best,

  Matteo

**Comment by mike5603** [comment]
There are two examples given in the Examples section of the code
