### ISSUE TITLE
GKC error

### ISSUE THREAD

**Issue by jnitlion** [MaginnGroup/PyLAT#19]
Hi! I am having a problem while trying to perform GKC calculations. The error says:

Traceback (most recent call last):
File "/path/PyLAT.py", line 246, in
(molcharges, atomcharges,n) = gc.getmolcharges(datfilename,n)
File "/path/PyLAT-master/src/getAtomCharges.py", line 77, in getmolcharges
molcharges[int(mol[int(atom)])-1] += atomcharges[int(atom)]
IndexError: index -1 is out of bounds for axis 0 with size 0

which I think is the same error raised in a closed issue (https://github.com/MaginnGroup/PyLAT/issues/12). I have a coarse-grained system (spheres) with charges and dipole moment. Attached are my trajectory and input files for your reference. Also, is there a specific values or info needed inside the log file?

I hope you can help me. Thanks!

[trajectory.txt](https://github.com/MaginnGroup/PyLAT/files/6833219/trajectory.txt)
[data.txt](https://github.com/MaginnGroup/PyLAT/files/6833220/data.txt)

**Comment by mike5603** [comment]
Unfortunately, the way PyLAT is coded assumes a certain formatting of the data files, which does not include dipole moments. The code is no longer in development, but I will try to write a quick hotfix that should help with this issue. Another thing to consider is that PyLAT does not support scaled units, so unscaled should be used in the trajectory file

**Comment by mike5603** [comment]
Please try adding the following at line 67 of getAtomCharges.py:

            elif len(line)==12:
                atomcharges[int(line[0])-1] = float(line[6])
                mol[int(line[0])-1] = int(line[5])

**Comment by jnitlion** [comment]
Thank you for your help, but another error appears:

Traceback (most recent call last):
  File "/path/PyLAT-master/PyLAT-master/PyLAT.py", line 247, in <module>
    molcharge = gc.molchargedict(molcharges, moltypel, moltype)
  File "/path/PyLAT-master/PyLAT-master/src/getAtomCharges.py", line 85, in molchargedict
    molcharge[moltypel[molecules]] = molcharges[moltype.index(molecules)]
IndexError: index 450 is out of bounds for axis 0 with size 1

This error always appear whatever number I put after the --nummol command. Fyi, I have 900 atoms in my system with two atom types so in my command I indicated:
 --nummol 450 --nummol 450 --mol atom1 --mol atom2

Again, thank you for your time and effort!

**Comment by mike5603** [comment]
For your data file, you have a molecule-id columns that is all ones. Is that what you want to use as the molecule id or do you want to use the atom id?

**Comment by jnitlion** [comment]
I want to use the atom-types. 1 is atom-type1 and 2 is the atom-type2 in my data file.
I am just confused about the --mol and --nummol flags. The --mol is the name of the molecule right? Should the name appear in the data file? The --nummol pertains to the number of molecules. In my system, that should be the number of atoms right? I could really use your clarification. Thank you so much!

**Comment by mike5603** [comment]
I'm looking at ids here not types. In your data file you have a column for molecule id, which you set as 1 for all of your atoms

**Comment by jnitlion** [comment]
Sorry for the confusion. In that case, I would like to use the atom id. Hoping for your help. Thank you!

**Comment by mike5603** [comment]
In that case for the code I asked you to add, replace `int(line[5])` with `int(line[0])`

**Comment by jnitlion** [comment]
Thanks for your help! I was able to fix the previous issues. However, I got a new error:

beginning GK conductivity calculation
Traceback (most recent call last):
  File "/path/PyLAT-master/PyLAT-master/PyLAT.py", line 285, in <module>
    output = cc.calcConductivity(molcharges, trjfilename, logfilename, datfilename, arg.temp, output, moltype, moltypel,arg.verbose,arg.GKC_skip,arg.GKC_Tolerance,arg.GKC_J_Output)
  File "/path/PyLAT-master/PyLAT-master/src/calcCond.py", line 51, in calcConductivity
    dotlist = self.getchargearrays(molcharges,moltype)
  File "/path/PyLAT-master/PyLAT-master/src/calcCond.py", line 331, in getchargearrays
    dotlist[i][k] = molcharges[k]
IndexError: index 500 is out of bounds for axis 0 with size 500

I attached here my updated input files (with correct data formatting) for your reference. Sorry to bother you repeatedly.
[trajectory.txt](https://github.com/MaginnGroup/PyLAT/files/6858209/trajectory.txt)
[datafile.txt](https://github.com/MaginnGroup/PyLAT/files/6858212/datafile.txt)

**Comment by mike5603** [comment]
how many atoms are in your system? Your comment above mentions 900 total, but your data file has 500

**Comment by jnitlion** [comment]
Oh my bad.. I updated my system so that it has 500 atoms in total just like what you have seen in the new data file. I corrected my command such that --nummol 250 nummol 250 --mol atom1 --mol atom2. Another error appears:

beginning GK conductivity calculation
beginning COM velocity calculation
Traceback (most recent call last):
  File "/path/PyLAT-master/PyLAT-master/PyLAT.py", line 285, in <module>
    output = cc.calcConductivity(molcharges, trjfilename, logfilename, datfilename, arg.temp, output, moltype, moltypel,arg.verbose,arg.GKC_skip,arg.GKC_Tolerance,arg.GKC_J_Output)
  File "/path/PyLAT-master/PyLAT-master/src/calcCond.py", line 61, in calcConductivity
    (jx, jy, jz, count) = self.calcj(dotlist, comvx, comvy, comvz, jx, jy, jz, count)
  File "/path/PyLAT-master/PyLAT-master/src/calcCond.py", line 181, in calcj
    jx[i][count] = np.dot(dotlist[i], comvx)
ValueError: matrices are not aligned

Thanks for your patience!

**Comment by mike5603** [comment]
Is there a reason you have a molecule id as 1 for everything? I would recommend initializing it such that each atom has a unique molecule id and that would fix a lot of your issues. Otherwise in the getcolumns function set `molcol = inline.index('id')`

**Comment by mike5603** [comment]
for the calcCond.py code

**Comment by jnitlion** [comment]
Thank you so much! It is working now. Do you suggest having large data measurements in the trajectory file for good convergence / accurate results?

**Comment by mike5603** [comment]
I think the more important thing for you to consider at this point is the frequency of measurement. In general, GKC requires very frequent measurements to get accurate results. I'm not sure what temperature you are running, but the example is NaCl at 1300 K, and it records the velocity every tilmestep. In general, how long you need to run your simulation and how frequently you sample varies for different systems, and is something you need to figure out.
