### ISSUE TITLE
No module named 'calccomf'

### ISSUE THREAD

**Issue by tatitechno** [MaginnGroup/PyLAT#2]
Hi,

I am facing this problem, no calccomf module exist after the compilation .. and I think others do : https://www.gitmemory.com/issue/MaginnGroup/PyLAT/1/507543737

Traceback (most recent call last):
  File "PyLAT.py", line 43, in <module>
    from src.calcCOM import calcCOM
  File "/lustre/home/elbentr81/PyLAT/src/calcCOM.py", line 26, in <module>
    import calccomf
ModuleNotFoundError: No module named 'calccomf'

python 3.6 , gcc/7.3.0 , 

thank you.
Regards.
Tayeb.

**Comment by mike5603** [comment]
Have you tried compiling using compile.py or compile.sh?

**Comment by tatitechno** [comment]
both of them, same result..

**Comment by mike5603** [comment]
what version of numpy are you using?

**Comment by mike5603** [comment]
the new compile.sh file should work for newer versions of numpy and python
