### ISSUE TITLE
Question about viscosity expression

### ISSUE THREAD

**Issue by Alexandrina-Chen** [MaginnGroup/PyLAT#30]
Dear PyLAT developers,

Thank you for writing this awesome package! I have a question about the calculation of viscosity, to be more specific, the average of the pressure tensor autocorrelation.

The original paper ([J. Chem. Theory Comput. 2015, 11, 3537−3546](https://pubs.acs.org/doi/10.1021/acs.jctc.5b00351)) doesn't describe how different components of the pressure tensor autocorrelation function are averaged ( $\lt P_{\alpha\beta}(t)P_{\alpha\beta}(0) \gt$ ). And according to another paper by Prof. Maginn, [Living J. Comp. Mol. Sci. 2019, 1(1), 6324](https://doi.org/10.33011/livecoms.1.1.6324), the average over the autocorrelation function of the traceless symmetric part of the stress tensor is recommended, as shown below
$$P_{\alpha\beta} = (\sigma_{\alpha\beta} + \sigma_{\beta\alpha}) / 2  -\frac{\delta_{\alpha\beta}}{3} (\sum_{\gamma} \sigma_{\gamma\gamma})$$

Then the viscosity is given by 
$$\eta=\frac{V}{10k_B T}\sum_{\sigma}\sum_{\beta}\int_0^{\inf} \lt P_{\alpha\beta}(t)P_{\alpha\beta}(0) \gt dt$$

The factor 10 in the denominator results from assigning weighting factors of 3/3 and 4/3 fir each of the six off-diagonal terms and the three diagonal terms, respectively. 

But in `visco.py` line 156 to 164

```
        a1=self.llog['pxy'][cutoff:]
        a2=self.llog['pxz'][cutoff:]
        a3=self.llog['pyz'][cutoff:]
        a4=self.llog['pxx'][cutoff:]-self.llog['pyy'][cutoff:]
        a5=self.llog['pyy'][cutoff:]-self.llog['pzz'][cutoff:]
        a6=self.llog['pxx'][cutoff:]-self.llog['pzz'][cutoff:]
        array_array=[a1,a2,a3,a4,a5,a6]
        pv=p.map(autocorrelate,array_array)
        pcorr = (pv[0]+pv[1]+pv[2])/6+(pv[3]+pv[4]+pv[5])/24
```
I didn't quite get the reason why the average is like this `(pv[0]+pv[1]+pv[2])/6+(pv[3]+pv[4]+pv[5])/24`, especially the denominators `6` and `24`. The off-diagonal terms in the equation above and the code share the same form and have nothing special. Then I have tried to transform the diagonal terms in the equation above into the expression of the code (namely, rewrite the autocorrelation of $P_{\alpha\alpha} = \sigma_{\alpha\alpha}   -\frac{\delta_{\alpha\beta}}{3} (\sum_{\gamma} \sigma_{\gamma\gamma})$ to the combination of the autocorrelations of $\sigma_{xx} - \sigma_{yy}$,  $\sigma_{xx} - \sigma_{zz}$,  and $\sigma_{yy} - \sigma_{zz}$), but I don't think they are equal.

I was wondering if there is any reason behind the weighting factors in the code, or if I can be guided to any paper that explain this. Thank you in advance!

Best,
Sijia

**Comment by zhangyongND** [comment]
Hi Sijia, in the code, we followed the convention from this paper: https://doi.org/10.1021/jp062885s.

**Comment by Alexandrina-Chen** [comment]
@zhangyongND Hi Yong, thank you a lot for guiding me to the paper!
