### ISSUE TITLE
Green-Kubo viscosity settings

### ISSUE THREAD

**Issue by lfafelipe** [MaginnGroup/PyLAT#8]
Dears,

I've been using the GK method to estimate the viscosity of some model fluids such as decane and hexadecane but my trajectores results don't behave like the ones presented in the article "**Reliable Viscosity Calculation from Equilibrium Molecular Dynamics Simulations: A Time Decomposition Method"**, i.e., my viscosity looks quite stable just after 1 ns and the standard deviation of my trajectores (10 samples) decreases as the timestep of my simulation increase.

I think that I am doing any mistake with the settings of the fix ave/correlate in LAMMPS. While reading the article "**Best Practices for Computing Transport Properties 1. Self-Duffusivity and Viscosity from Equilibrium Molecular Dynamics**", I've noticed that I am having trouble in understanding the difference between the Green-Kubo integration time and the simulation length. 

The integration time can be adjusted by tweaking the parameters Nevery, Nfreq and Nrepeat in the fix ave/correlate command in LAMMPS. Is this correct? For example, by setting the parameters Nevery = 1000, Nfreq = 10 and Nrepeat = 1000*10 with a timestep of 1 fs means that the correlation length (integration time) is 10 ps.

I think that these settings can explain why my viscosity integral does not look like the results in the article mentioned. 

Could you please share your thoughts on this? 

Thank you very much.

**Comment by mike5603** [comment]
This area is for questions specific to the PyLAT codes. For more general LAMMPS questions, I would use the LAMMPS mailing list
