### ISSUE TITLE
Issue and error on installation of PyLAT

### ISSUE THREAD

**Issue by maaaslani11** [MaginnGroup/PyLAT#9]
I would like to use PyLAT that you developed in your group. When I want to install via “pip install PyLAT” on my computer (Windows 10), it made an error and the tool was not installed. The error is as below, if you could give me an idea of how to fix this issue, I would be very appreciated.  
Thanks   
Mahmoud ASLANI
 
(PyLAT) C:\Users\acer\Anaconda3\envs>pip install pylat
Collecting pylat
  Using cached pylat-0.2.1-py3-none-any.whl (34 kB)
  Using cached pylat-0.2.0-py3-none-any.whl (34 kB)
ERROR: Cannot install pylat==0.2.0 and pylat==0.2.1 because these package versions have conflicting dependencies.
 
The conflict is caused by:
    pylat 0.2.1 depends on en-core-web-sm
    pylat 0.2.0 depends on en-core-web-sm
 
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
 
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

**Comment by mike5603** [comment]
The Pylat in pip is not this code. To install this code, please download directly from github

**Comment by maaaslani11** [comment]
Thank you, but the same error again was made, when downloading directly from github.

**Comment by mike5603** [comment]
You must still be downloading the wrong code. We do not have version numbers for this code, so it is impossible to have version conflicts between versions. Also, the dependency you mentioned is from an nlp code which the other pylat does
